// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emrfbajprkkcpmtfcrak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtcmZiYWpwcmtrY3BtdGZjcmFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMDQ3NjksImV4cCI6MjA2MTc4MDc2OX0.96uKtcx-Q72uq0d9GHSSZvEzDoHX0vx9dQjUCpKIKIw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);